# 如果设置 Action1Run1="/app3/action1run1" 那么不需要加appname 
# 如果设置 Action1Run1="action1run1" 那么需要加appname ，判断依据是否／开始

# header 的处理

[[action]]
DoHeader="header"
DoSubHeader="subheader"

[[gml]]
header_frame="view/header.gml"
subheader_frame="view/subheader.gml"
